### ISSUE TITLE
Get error with Chart.js

### ISSUE THREAD

**Issue by ry815** [yasminzy/website#2]
I installed vue chart.js by following your tutorial on my nuxt project.

After adding bar chart, it shows transition error.

![image](https://user-images.githubusercontent.com/28104782/56437284-9e79ae80-6293-11e9-98be-76c150dd0e47.png)

It seems it was cursed because of initializing the graph with animation.
I want to disable animation like this. 

![image](https://user-images.githubusercontent.com/28104782/56437363-ec8eb200-6293-11e9-9940-2bd4e629a6a2.png)

But not sure how to do that.
Please help me with that.

**Comment by yasminzy** [comment]
Hi @ry815 . Sorry, I wasn't active. You may have already solved the issue by now haha 😅

The way to override option isn't different with backgroundcolor, data, labels, etc.

Let me give you an example. In `your-component.vue`:
```html
<template>
  <div>
    <chartjs-bar
      :backgroundcolor="bgColor"
      :bind="true"
      :data="data"
      :labels="labels"
      :option="option"
    />
  </div>
</template>
```
```js
<script>
export default {
  data() {
    return {
      bgColor: "#de98ab",
      data: [1, 3, 5, 7, 2, 4, 6],
      labels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      option: {
        responsive: true,
        maintainAspectRatio: true,
        animation: {
          duration: 0
        },
        hover: {
          animationDuration: 0
        },
        responsiveAnimationDuration: 0
      }
    };
  }
};
</script>
```
You can find the docs [here](http://vue-charts.hchspersonal.tk/bar#option). Hope this help!
